# .github/workflows/ci.yml
name: SecureShare Chat CI

on:
  push:
    branches: [ "main" ] # Or your primary branch name
  pull_request:
    branches: [ "main" ] # Or your primary branch name

permissions:
  contents: read

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x] # Use the LTS version specified or preferred version

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm' # Cache npm dependencies

    - name: Install dependencies
      run: npm ci # Use 'npm ci' for cleaner installs in CI

    - name: Build project
      run: npm run build

    - name: Run linter
      run: npm run lint

    - name: Run type checking
      run: npm run typecheck
      
    # Add tests step if you have tests configured
    # - name: Run tests
    #   run: npm test
